import os
import ast

def boolify(value):
  return True if value.lower() == "true" else False

PUPPETDB_HOST = os.environ['PUPPETBOARD_PUPPETDB_HOST']
PUPPETDB_PORT = int(os.environ['PUPPETBOARD_PUPPETDB_PORT'])
PUPPETDB_SSL_VERIFY = boolify(os.environ['PUPPETBOARD_PUPPETDB_SSL_VERIFY'])
PUPPETDB_KEY = os.environ['PUPPETBOARD_PUPPETDB_KEY'] if os.environ['PUPPETBOARD_PUPPETDB_KEY'] else None
PUPPETDB_CERT = os.environ['PUPPETBOARD_PUPPETDB_CERT'] if os.environ['PUPPETBOARD_PUPPETDB_CERT'] else None
PUPPETDB_TIMEOUT = int(os.environ['PUPPETBOARD_PUPPETDB_TIMEOUT'])
DEFAULT_ENVIRONMENT = os.environ['PUPPETBOARD_DEFAULT_ENVIRONMNET']
SECRET_KEY = os.urandom(24)
UNRESPONSIVE_HOURS = int(os.environ['PUPPETBOARD_UNRESPONSIVE_HOURS'])
ENABLE_QUERY = boolify(os.environ['PUPPETBOARD_ENABLE_QUERY'])
LOCALISE_TIMESTAMP = boolify(os.environ['PUPPETBOARD_LOCALISE_TIMESTAMP'])
LOGLEVEL = os.environ['PUPPETBOARD_LOGLEVEL']
REPORTS_COUNT = int(os.environ['PUPPETBOARD_REPORTS_COUNT'])
OFFLINE_MODE = boolify(os.environ['PUPPETBOARD_OFFLINE_MODE'])
ENABLE_CATALOG = boolify(os.environ['PUPPETBOARD_ENABLE_CATALOG'])
OVERVIEW_FILTER = os.environ['PUPPETBOARD_OVERVIEW_FILTER'] if os.environ['PUPPETBOARD_OVERVIEW_FILTER'] else None
GRAPH_FACTS = ' '.split(os.environ['PUPPETBOARD_GRAPH_FACTS']) if 'PUPPETBOARD_GRAPH_FACTS' in os.environ else []
INVENTORY_FACTS = list(ast.literal_eval(os.environ['PUPPETBOARD_INVENTORY_FACTS'])) if 'PUPPETBOARD_INVENTORY_FACTS' in os.environ else []
REFRESH_RATE = int(os.environ['PUPPETBOARD_REFRESH_RATE'])
